### PR TITLE
Issue #22 - Improve the notification message

### PR DESCRIPTION
**Pull request by aliuk2012**
A few corrections to the notification as per issue #22

### CODE REVIEW

**Comment by janodvarko** [comment]
Nice, thanks!
One question, why there is 'but' in '...but among other things, ...' ?

Honza

**Comment by aliuk2012** [comment]
Changes made...and I noticed the recent move to notification.properties

**Comment by janodvarko** [comment]
Excellent, nit: one exclamation mark at the end is enough.

Honza

**Comment by aliuk2012** [comment]
done

**Comment by janodvarko** [comment]
Thanks!

Honza

**Pull request merged**
