### PR TITLE
New icon design based on proper vector version

### PR DESCRIPTION
**Pull request by mbuckley**
- Added 64x64 version

### CODE REVIEW

**Comment by janodvarko** [comment]
Nice!

Honza

**Comment by SebastianZ** [comment]
The vector image should be added to the repository, too, so it can be reused later.

Sebastian

**Comment by mbuckley** [comment]
@SebastianZ I'll get a copy of that and add it to the repo.

@janodvarko Where should the vector source image live in the repository? We could create a src folder in the skin folder..

**Comment by janodvarko** [comment]
@ibuck: please put it into docs/images
https://github.com/firebug/pixel-perfect/tree/master/docs/images

The 'docs' dir is not included in the final XPI.

Honza

**Pull request merged**
